set -g default-terminal "screen-256color"

setw -g mode-keys vi
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
setw -g automatic-rename on
setw -g automatic-rename-format '#{b:pane_current_path}'
set -g history-limit 50000
set -sg escape-time 0
set -g repeat-time 500
set -g focus-events on

set -g mouse on

set -g monitor-activity on
set -g visual-activity on

set -g prefix C-x
unbind C-b
bind C-x send-prefix

bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

bind c new-window -c "#{pane_current_path}"
bind , command-prompt -I "#W" "rename-window '%%'"
bind s choose-tree -Zs
bind w choose-tree -Zw
bind S command-prompt -p "New session name:" "new-session -s '%%'"

bind x confirm-before -p "Kill pane? (y/n)" kill-pane
bind & confirm-before -p "Kill window? (y/n)" kill-window

bind r source-file ~/.tmux.conf \; display-message "Config reloaded!"

bind m set -g mouse \; display-message "Mouse mode: #{?mouse,on,off}"

bind ? list-keys
# Styling
RED="#ebdbb2"
GREEN="#b8bb26"
YELLOW="#fabd2f"
BLUE="#83a598"
MAGENTA="#d3869b"
CYAN="#8ec07c"
BLACK="#282828"
DARKGRAY="#665C54"
LIGHTGRAY="#ebdbb2"

# base status bar
set -g status on
set -g status-interval 5
set -g status-justify centre
set -g status-style "bg=${BLACK} fg=${LIGHTGRAY}"

setw -g window-status-style "bg=${BLACK} fg=${DARKGRAY}"
setw -g window-status-current-style "bg=${DARKGRAY} fg=${LIGHTGRAY}"
setw -g window-status-activity-style "bg=${BLACK} fg=${YELLOW}"

setw -g window-status-format " #I:#W "
setw -g window-status-current-format " #I:#W "

set -g status-left-length 40
set -g status-left "#[bg=${BLACK},fg=${GREEN},bold] #S #[bg=${BLACK},fg=${LIGHTGRAY}]"

set -g status-right-length 80
set -g status-right "#[bg=${BLACK},fg=${DARKGRAY}] | #[fg=${CYAN}] #(whoami)@#H #[bg=${BLACK},fg=${LIGHTGRAY}]"

#######

set -g pane-border-style "fg=${DARKGRAY}"
set -g pane-active-border-style "fg=${BLUE}"
set -g message-style "bg=${BLACK} fg=${YELLOW}"
set -g mode-style "bg=${DARKGRAY} fg=${LIGHTGRAY}"

